name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # إصدار مستقر
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get
        working-directory: ./auraguard # المسار اللي فيه ملف pubspec.yaml

      - name: Build APK
        run: flutter build apk --release --split-per-abi
        working-directory: ./auraguard

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: auraguard/build/app/outputs/flutter-apk/*.apk
